Fix/88/follow dto&reply dto
sb3827/TourInfoServiceServer pull request #105
Opened 2024-01-24 04:23 UTC by yununyu

2024-01-25 03:45 UTC, sb3827 requested changes
충돌 수정부터 해주세요

2024-01-26 01:17 UTC, yununyu commented
> 충돌 수정부터 해주세요

충돌 수정했습니다

2024-01-26 11:01 UTC, sb3827 approved these changes

2024-01-26 11:01 UTC, sb3827 commented on src/main/java/com/dot/tour_info_service_server/dto/request/reply/ReplyRequestDTO.java
ReplyRequestDTO 어디에서 사용되는지 알 수 있을까요??

2024-01-29 00:51 UTC, yununyu commented on src/main/java/com/dot/tour_info_service_server/dto/request/reply/ReplyRequestDTO.java
댓글 달거나 수정할 때 사용합니당.

2024-01-29 00:51 UTC, merged